# Configuracion de SQL Server 2022
# Documentacion: https://learn.microsoft.com/sql/linux/sql-server-linux-configure-mssql-conf

[memory]
memorylimitmb=0

[sqlagent]
enabled=false

[telemetry]
customerfeedback=false
